"""It is necessary to update the names and charges of APTES chains
when their protonation changes to read the correct parameters from the
Forcefield data files. The changes that need to be made are as
follows:

"""

import sys
import numpy as np
import pandas as pd
import ionization
from colors_text import TextColor as bcolors


class UpdateAptesDf:
    """Updates APTES dataframe, by adding the hydrogens. Based on the
    positions, we have to make H atoms to be added to the pdb file"""

    update_aptes: pd.DataFrame  # Updated apted chains

    def __init__(self,
                 atoms: pd.DataFrame,  # All atoms coordinates
                 df_aptes: pd.DataFrame,  # All the APTES informations
                 h_positions: dict[int, np.ndarray]  # Index and coordinates
                 ) -> None:
        self.update_aptes = self.update_aptes_df(atoms, df_aptes, h_positions)

    def update_aptes_df(self,
                        atoms: pd.DataFrame,  # All the atoms info
                        df_aptes: pd.DataFrame,  # Aptes chains
                        h_positions: dict[int, np.ndarray]  # Pos for H
                        ) -> pd.DataFrame:
        """update the aptes dataframe by adding new HN3 atoms"""
        nh3_atoms: pd.DataFrame = self.__prepare_hydrogens(atoms, h_positions)
        return self.__append_hydrogens(df_aptes, nh3_atoms)

    @staticmethod
    def __append_hydrogens(df_aptes: pd.DataFrame,  # Aptes chains
                           hn3_atoms: pd.DataFrame  # H atoms to append
                           ) -> pd.DataFrame:
        """append NH3 atoms to the main df"""
        return pd.concat([df_aptes, hn3_atoms], ignore_index=False)

    @staticmethod
    def __prepare_hydrogens(atoms: pd.DataFrame,  # All the atoms info
                            h_positions: dict[int, np.ndarray]  # Pos for H
                            ) -> pd.DataFrame:
        """prepare the aptes based on the structure of the main df"""
        final_atom: int = atoms.iloc[-1]['atom_id']
        cols: list[str] = ['records', 'atom_id', 'atom_name',
                           'residue_number', 'residue_name', 'x', 'y', 'z',
                           'occupancy', 'temperature', 'atom_symbol']
        hn3_atoms: pd.DataFrame = pd.DataFrame(columns=cols)

        for i, (key, value) in enumerate(h_positions.items()):
            hn3_atoms.loc[i] = \
                ['ATOM', final_atom + i + 1, 'HN3', key, 'APT', value[0],
                 value[1], value[2], 1.0, 0.0, 'H']

        return hn3_atoms


class WritePdbTest:
    """write pdb file from Pdb class in lmpdb"""
    def __init__(self,
                 pdb_df: pd.DataFrame,  # df in pdb format
                 fname: str  # Input file name of LAMMPS data
                 ) -> None:
        self.pdb_file: str = self.write_pdb(pdb_df, fname)

    def write_pdb(self,
                  pdb_df: pd.DataFrame,  # df in pdb format
                  fname: str  # Input file name of LAMMPS data
                  ) -> str:
        """write the dataframe into a file"""
        fout: str  # Name of the output file
        fout = self.rename_file(fname, extension='pdb')
        print(f'{bcolors.OKBLUE}{self.__class__.__name__}: '
              f'({self.__module__})\n'
              f'\tPDB file is `{fout}`{bcolors.ENDC}\n')
        pdb_df['records'] = ['ATOM' for _ in range(len(pdb_df))]
        pdb_df['occupancy'] = [' ' for _ in range(len(pdb_df))]
        # pdb_df['atom_id'] = [' ' for _ in range(len(pdb_df))]
        pdb_df['temperature'] = [' ' for _ in range(len(pdb_df))]
        pdb_df['Segment_id'] = [' ' for _ in range(len(pdb_df))]
        pdb_df['charge'] = [' ' for _ in range(len(pdb_df))]
        pdb_df['element'] = [' ' for _ in range(len(pdb_df))]
        with open(fout, 'w', encoding="utf8") as f_w:
            f_w.write('HEADER\n')
            f_w.write('REMARK    GENERATED BY TRJCONV\n')
            f_w.write('TITLE     silica_water\n')
            f_w.write('REMARK    THIS IS A SIMULATION BOX\n')
            f_w.write('CRYST1  219.280  219.280  209.526  90.00  90.00')
            f_w.write('  90.00 P 1           1\n')
            f_w.write('MODEL        1\n')
            for row in pdb_df.iterrows():
                line: list[str]  # line with length of pdb line fill by spaces
                line = [' '*79]
                line[0:6] = f'{row[1]["records"]:<6s}'
                line[6:11] = f'{row[1]["atom_id"]:>5d}'
                line[11:12] = ' '
                line[12:16] = f'{row[1]["atom_name"]:<4s}'
                line[16:17] = ' '
                line[17:20] = f'{row[1]["residue_name"]:<3s}'
                line[20:22] = f'{" "*2}'
                line[22:26] = f'{row[1]["residue_number"]:>4d}'
                line[26:27] = ' '
                line[27:30] = f'{" "*3}'
                line[30:38] = f'{row[1]["x"]:>8.3f}'
                line[38:46] = f'{row[1]["y"]:>8.3f}'
                line[46:54] = f'{row[1]["z"]:>8.3f}'
                line[54:60] = f'{row[1]["occupancy"]:>6.2s}'
                line[60:66] = f'{row[1]["temperature"]:>6s}'
                line[66:72] = f'{" "*6}'
                line[72:76] = f'{row[1]["Segment_id"]:<4s}'
                line[76:78] = f'{row[1]["element"]:>2s}'
                line[78:] = f'{row[1]["charge"]:2s}'
                f_w.write(''.join(line))
                f_w.write('\n')
            f_w.write('END\n')
        return fout

    @staticmethod
    def rename_file(fname: str,  # Input file name
                    extension: str  # The extension of the output file
                    ) -> str:  # Out put file name
        """rename file name, same name with pdb extension"""
        fout: str  # Output file name
        fout = f'{fname.strip().split(".")[0]}.{extension}'
        return fout


if __name__ == '__main__':
    data = ionization.IonizationSol(sys.argv[1])
    updated = UpdateAptesDf(data.atoms,
                            data.residues_atoms['APT'],
                            data.h_porotonations)
    WritePdbTest(updated.update_aptes, 'APTES3')
    WritePdbTest(data.residues_atoms['SOL'], 'SOL')
